services:
    mongodb:
        image: mongo:8.0.13-noble
        container_name: mongodb
        ports:
          - "27007:27017"
        volumes:
          - ./mongodb:/data/db
        networks:
          - backend
        restart: always

networks:
  backend:
